# -*- coding: utf-8 -*-
# Auto-generated by build.py
# Please do not manually edit anything other than the contents of main.py.

from hub import motion_sensor
from hub import port
from hub import sound
import color
import color_sensor
import distance_sensor
import force_sensor
import motor_pair
import random
import runloop

# ────────────────────────────────────────────────────────
# constants.py
# ────────────────────────────────────────────────────────
# モーターペア
M_PAIR = motor_pair.PAIR_1


# インターバル時間（ミリ秒）
WHILE_INTERVAL = 10


# 音量
SOUND_VOLUME = 75

# 黒色の反射率（0～35%）
BLACK_REFLECTION_MIN = 0.0
BLACK_REFLECTION_MAX = 35.0

# 黒色の反射率（35～55%）
DARK_GREY_REFLECTION_MIN = 35.0
DARK_GREY_REFLECTION_MAX = 55.0

# 黒色の反射率（55～75%）
LIGHT_GREY_REFLECTION_MIN = 55.0
LIGHT_GREY_REFLECTION_MAX = 75.0

# ユーティリティ計算用
M_MOTOR_MAX_VELOCITY = 1110
DEGREES_PER_CM = 20.5

# 正確な回転関連の定数
YAW_SCALE = 10  # 0.1°単位の矯正用（900→90°, 45°→450）
ROTATION_KP = 0.05  # 速度制御定数
ANGLE_TOLERANCE = 10  # 許容誤差：1°
MIN_ROTATION_POWER = 5

# ライントレース用
LINE_TRACE_ROTATION_KP = 1.5
LINE_TRACE_MAX_STEERING = 100


# ────────────────────────────────────────────────────────
# utils\orientation.py
# ────────────────────────────────────────────────────────
def get_yaw():
    return motion_sensor.tilt_angles()[0]


def reset_yaw_value():
    motion_sensor.reset_yaw(0)


# ────────────────────────────────────────────────────────
# sensors\color_sensor.py
# ────────────────────────────────────────────────────────
# 色

def is_detected_black(color_value: int):
    """ colorの値が黒かどうかを判定する """
    return color_value == color.BLACK


def is_detected_red(color_value: int):
    """ colorの値が赤かどうかを判定する（たまにUNKNOWNと判定することがある） """
    return (color_value == color.RED) or (color_value == color.UNKNOWN)


def is_detected_green(color_value: int):
    """ colorの値が緑かどうかを判定する """
    return color_value == color.GREEN


def is_detected_blue(color_value: int):
    """ colorの値が青かどうかを判定する """
    return color_value == color.BLUE


def any_sensor_detects_by_color(predicate, *ports: int) -> bool:
    """ 判定関数を使用してセンサーのうちの1つでも指定された色が検知されているかを判定する """
    return any(predicate(color_sensor.color(port)) for port in ports)


# 反射率

def is_reflection_in_range(reflection: int, range_min: int, range_max: int):
    """ 最低値と最大値の中に反射率が収まっているか判定する """
    return range_min <= reflection <= range_max


def get_reflection_difference(port1: int, port2: int) -> int:
    """ ポート1とポート2の反射率の差を返す """
    return color_sensor.reflection(port1) - color_sensor.reflection(port2)


def any_sensor_detects_by_reflection(range_min: int, range_max: int, *ports: int) -> bool:
    """ センサーの反射率のうち1つでも指定の範囲に収まっているかを判定する """
    return any(is_reflection_in_range(color_sensor.reflection(port), range_min, range_max) for port in ports)


def all_sensor_detects_by_reflection(range_min: int, range_max: int, *ports: int) -> bool:
    """ センサーの反射率のうちすべてが指定の範囲に収まっているかを判定する """
    return all(is_reflection_in_range(color_sensor.reflection(port), range_min, range_max) for port in ports)


# ────────────────────────────────────────────────────────
# utils\calc.py
# ────────────────────────────────────────────────────────
def clamp(value: float, minimum: int, maximum: int):
    return int(max(min(value, maximum), minimum))


# ────────────────────────────────────────────────────────
# enums.py
# ────────────────────────────────────────────────────────
class DistanceUnit:
    """ 距離の単位を表す（関数の引数に指定） """
    M = "m"
    CM = "cm"
    MM = "mm"


# ────────────────────────────────────────────────────────
# sensors\force_sensor.py
# ────────────────────────────────────────────────────────
def get_force(port: int) -> int:
    """ フォースセンサー（のボタン）の押されている強さを取得する（0~100） """
    return force_sensor.force(port)


def is_button_pressed(*ports: int) -> bool:
    """ フォースセンサーが押されているかを判定する """
    return any(force_sensor.pressed(port) for port in ports)


async def wait_for_button_release(port: int) -> None:
    """ フォースセンサーが離されるまで待つ（すでに押されている状態から） """
    while is_button_pressed(port):
        await runloop.sleep_ms(WHILE_INTERVAL)


async def wait_for_button_click(port: int) -> None:
    """ フォースセンサーが押されて離されるまで待つ """
    while not is_button_pressed(port):
        await runloop.sleep_ms(WHILE_INTERVAL)

    await wait_for_button_release(port)


# ────────────────────────────────────────────────────────
# setup.py
# ────────────────────────────────────────────────────────
# モーターペアの初期化
motor_pair.pair(M_PAIR, port.C, port.D)


# ────────────────────────────────────────────────────────
# utils\conversions.py
# ────────────────────────────────────────────────────────
def cm_to_degrees(cm: int):
    """ 距離〔cm〕を角度に変換する（410度で20cm換算） """
    return int(cm * DEGREES_PER_CM)


def power_percentage_to_velocity(power: int):
    """  パワー（%）をVelocityの数値に変換する（Mモーター用） """
    return int(M_MOTOR_MAX_VELOCITY * power / 100)


# ────────────────────────────────────────────────────────
# utils\sounds.py
# ────────────────────────────────────────────────────────
NOTE_HZ_MAP = {
    "C3": 131, "C#3": 139, "D3": 147, "D#3": 156, "E3": 165,
    "F3": 175, "F#3": 185, "G3": 196, "G#3": 208, "A3": 220,
    "A#3": 233, "B3": 247,

    "C4": 262, "C#4": 277, "D4": 294, "D#4": 311, "E4": 330,
    "F4": 349, "F#4": 370, "G4": 392, "G#4": 415, "A4": 440,
    "A#4": 466, "B4": 494,

    "C5": 523, "C#5": 554, "D5": 587, "D#5": 622, "E5": 659,
    "F5": 698, "F#5": 740, "G5": 784, "G#5": 831, "A5": 880,
    "A#5": 932, "B5": 988,
}

NOTE_NAME_MAP = {
    "ド": "C",
    "レ": "D",
    "ミ": "E",
    "ファ": "F",
    "ソ": "G",
    "ラ": "A",
    "シ": "B",
}


def get_note_hz(note: str) -> int:
    """
    音名から周波数を取得する

    例:
        get_note_hz("ド4")
        get_note_hz("ド#4")
        get_note_hz("ソ3")
        get_note_hz("ラ#5")
    """

    for jp, en in NOTE_NAME_MAP.items():
        if note.startswith(jp):
            note = en + note[len(jp):]
            break
    else:
        raise ValueError("無効な音名: " + note)

    if len(note) >= 3 and note[1].isdigit() and note[2] == "#":
        note = note[0] + "#" + note[1]

    try:
        return NOTE_HZ_MAP[note]
    except KeyError:
        raise ValueError("対応していない音程: " + note)


async def play_sound(hz: int, time: int):
    """ 指定された周波数の音を再生する """
    await sound.beep(int(hz * 2), time, SOUND_VOLUME)
    await runloop.sleep_ms(1)


def bpm_to_note_durations_ms(bpm: int) -> tuple[int, int, int]:
    """ BPMから4分音符・8分音符・16分音符の長さをミリ秒単位に変換する """
    quarter_note_ms = int(60000 / bpm)
    eighth_note_ms = int(quarter_note_ms / 2)
    sixteenth_note_ms = int(eighth_note_ms / 2)

    return quarter_note_ms, eighth_note_ms, sixteenth_note_ms


# ────────────────────────────────────────────────────────
# estimators\orientation_estimator.py
# ────────────────────────────────────────────────────────
def get_data_for_precise_rotation(target_angle: int) -> tuple[int, bool]:
    """ ロボットの姿勢からパワーと誤差を計算する """

    current_yaw_angles = get_yaw()  # 0.1°単位（900で90°）
    diff = target_angle * YAW_SCALE - current_yaw_angles
    is_finished = abs(diff) <= ANGLE_TOLERANCE

    if is_finished:
        return 0, True

    max_power = MIN_ROTATION_POWER * 8  # 5 * 8 = 40

    if 600 > abs(diff) > 300:        # 30～60°
        max_power = MIN_ROTATION_POWER * 4  # 5 * 4 = 20
    elif 300 > abs(diff) > 100:        # 10～30°
        max_power = MIN_ROTATION_POWER * 2  # 5 * 2 = 10
    elif 100 > abs(diff):                        # 10°未満
        max_power = MIN_ROTATION_POWER  # 5 * 1 = 5

    power = clamp(diff * ROTATION_KP, -max_power, max_power)

    if 0 < power < MIN_ROTATION_POWER:
        power = MIN_ROTATION_POWER
    elif -MIN_ROTATION_POWER < power < 0:
        power = -MIN_ROTATION_POWER

    return power, False


# ────────────────────────────────────────────────────────
# sensors\distance_sensor.py
# ────────────────────────────────────────────────────────
def get_distance_in_mm(port: int):
    """ 距離センサーから距離（mm）を取得する """

    return distance_sensor.distance(port)


def _convert_value_to_mm(value: int, unit: str):
    if unit == DistanceUnit.MM:
        return value
    if unit == DistanceUnit.CM:
        return value * 10
    if unit == DistanceUnit.M:
        return value * 10 * 100

    raise ValueError("Unsupported distance unit: " + unit)


def is_distance_less_than_or_equal(port: int, value: int, unit: str):
    """ 距離が指定の値以下かを判定する（unitにはDistanceUnitを指定可能） """

    distance = get_distance_in_mm(port)

    if distance == -1:
        return False

    value = _convert_value_to_mm(value, unit)

    return distance <= value


def is_distance_greater_than_or_equal(port: int, value: int, unit: str):
    """ 距離が指定の値以上かを判定する（unitにはDistanceUnitを指定可能） """

    distance = get_distance_in_mm(port)

    if distance == -1:
        return False

    value = _convert_value_to_mm(value, unit)

    return distance >= value


# ────────────────────────────────────────────────────────
# sounds\songs.py
# ────────────────────────────────────────────────────────
# Octave 3
do_3 = get_note_hz('ド3')
do_3_s = get_note_hz('ド3#')
re_3 = get_note_hz('レ3')
re_3_s = get_note_hz('レ3#')
mi_3 = get_note_hz('ミ3')
fa_3 = get_note_hz('ファ3')
so_3 = get_note_hz('ソ3')
so_3_s = get_note_hz('ソ3#')
la_3 = get_note_hz('ラ3')
la_3_s = get_note_hz('ラ3#')
ti_3 = get_note_hz('シ3')

# Octave 4
do_4 = get_note_hz('ド4')
do_4_s = get_note_hz('ド4#')
re_4 = get_note_hz('レ4')
re_4_s = get_note_hz('レ4#')
mi_4 = get_note_hz('ミ4')
fa_4 = get_note_hz('ファ4')
so_4 = get_note_hz('ソ4')
so_4_s = get_note_hz('ソ4#')
la_4 = get_note_hz('ラ4')
la_4_s = get_note_hz('ラ4#')
ti_4 = get_note_hz('シ4')

# Octave 5
do_5 = get_note_hz('ド5')
do_5_s = get_note_hz('ド5#')
re_5 = get_note_hz('レ5')
re_5_s = get_note_hz('レ5#')
mi_5 = get_note_hz('ミ5')
fa_5 = get_note_hz('ファ5')
so_5 = get_note_hz('ソ5')
so_5_s = get_note_hz('ソ5#')
la_5 = get_note_hz('ラ5')
la_5_s = get_note_hz('ラ5#')
ti_5 = get_note_hz('シ5')


async def yajuu():
    """ YAJU&U (モチモチ) を演奏する """
    n4, n8, n16 = bpm_to_note_durations_ms(bpm=100)

    await play_sound(so_4, n8)
    await play_sound(la_4_s, n8)
    await play_sound(so_4, n8)
    await play_sound(la_4_s, n8)
    await play_sound(re_5_s, n4)

    await play_sound(la_4, n8)
    await play_sound(re_5, n8)
    await play_sound(fa_4, n8)

    await play_sound(re_5, n8)
    await play_sound(do_5, n8)
    await play_sound(re_5, n8)
    await play_sound(fa_5, n4)

    await play_sound(so_4, n8)
    await play_sound(so_4, n8)
    await play_sound(re_4, n8)
    await play_sound(so_4, n8)
    await play_sound(la_4, n8)
    await play_sound(la_4_s, n8)
    await play_sound(so_3, n4)

    await play_sound(la_3_s, n8)
    await play_sound(do_4, n8)
    await play_sound(re_4, n8)
    await play_sound(do_4, n8)
    await play_sound(la_3_s, n8)
    await play_sound(la_3_s, n4 + n8)
    await runloop.sleep_ms(n8)

    await play_sound(la_4_s, n4)
    await play_sound(la_4_s, n8)
    await play_sound(re_4_s, n8)
    await play_sound(so_4, n8)
    await play_sound(re_4_s, n8)
    await play_sound(la_4_s, n8)
    await runloop.sleep_ms(n16)

    await play_sound(so_4, n8 + n16)
    await play_sound(fa_4, n8)
    await play_sound(re_4_s, n8)
    await play_sound(re_4, n8)
    await play_sound(do_4_s, n8)
    await play_sound(re_4, n8)
    await runloop.sleep_ms(n8)

    await play_sound(fa_4, n8)
    await play_sound(so_4, n8)
    await play_sound(so_4, n8)
    await play_sound(la_4_s, n4)
    await play_sound(so_4, n4)
    await play_sound(la_4_s, n4)

    await play_sound(re_5, n4 + n8)
    await play_sound(do_5, n8)
    await play_sound(la_4_s, n8)
    await play_sound(so_4, n8)
    await play_sound(la_4_s, n8)
    await runloop.sleep_ms(n8)

    await play_sound(la_4_s, n4)
    await play_sound(la_4_s, n8)
    await play_sound(re_4_s, n8)
    await play_sound(so_4, n8)
    await play_sound(re_4_s, n8)
    await play_sound(la_4_s, n8)
    await runloop.sleep_ms(n16)

    await play_sound(so_4, n8 + n16)
    await play_sound(fa_4, n8)
    await play_sound(re_4_s, n8)
    await play_sound(re_4, n8)
    await play_sound(do_4_s, n8)
    await play_sound(re_4, n8)
    await runloop.sleep_ms(n8)

    await play_sound(fa_4, n8)
    await play_sound(so_4, n8)
    await play_sound(so_4, n8)
    await play_sound(la_4_s, n4)
    await play_sound(so_4, n4)
    await play_sound(la_4_s, n4)

    await play_sound(la_4_s, n8)
    await play_sound(so_4, n16)
    await play_sound(la_4_s, n8)
    await play_sound(so_4, n16)
    await play_sound(do_5, n8)
    await play_sound(la_4_s, n4)


async def tidus():
    """ コネクト (Claris) （おとわっかVer） を演奏する """
    n4, n8, _ = bpm_to_note_durations_ms(bpm=175)

    await play_sound(la_4_s, n8)
    await play_sound(la_4, n8)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n8)

    await play_sound(re_5, n4 + n8)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n8)
    await play_sound(re_5, n4)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n8)
    await play_sound(re_5, n8)
    await play_sound(re_5, n8)
    await play_sound(fa_5, n4)
    await play_sound(do_5, n8)
    await runloop.sleep_ms(n8)

    await play_sound(do_5, n4 + n8)
    await play_sound(do_5, n8)
    await play_sound(la_4, n8)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n4)
    await play_sound(la_4, n8)
    await play_sound(do_5, n8)
    await play_sound(la_4_s, n8)
    await play_sound(la_4, n8)
    await play_sound(la_4_s, n8)
    await runloop.sleep_ms(n8)

    await play_sound(la_4, n8)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n8)

    await play_sound(re_5, n4 + n8)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n8)
    await play_sound(re_5, n4)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n8)
    await play_sound(re_5, n8)
    await play_sound(re_5, n8)
    await play_sound(fa_5, n4)
    await play_sound(do_5, n8)
    await runloop.sleep_ms(n8)

    await play_sound(do_5, n4)
    await play_sound(do_5, n8)
    await play_sound(do_5, n8)
    await play_sound(do_5, n8)
    await play_sound(do_5, n8)
    await play_sound(ti_4, n8)
    await play_sound(do_5, n8)
    await play_sound(re_5, n4 * 2)
    await runloop.sleep_ms(n8)

    await play_sound(la_4_s, n8)
    await play_sound(la_4, n8)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n8)

    await play_sound(re_5, n4 + n8)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n8)
    await play_sound(re_5, n4)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n8)
    await play_sound(re_5, n8)
    await play_sound(re_5, n8)
    await play_sound(fa_5, n4)
    await play_sound(do_5, n8)
    await runloop.sleep_ms(n8)

    await play_sound(do_5, n4 + n8)
    await play_sound(do_5, n8)
    await play_sound(la_4, n8)
    await play_sound(la_4_s, n8)
    await play_sound(do_5, n4)
    await play_sound(la_4, n8)
    await play_sound(fa_5, n8)
    await play_sound(re_5_s, n8)
    await play_sound(re_5, n8)
    await play_sound(la_4_s, n4)

    await play_sound(la_4, n8)
    await play_sound(la_4, n8)
    await play_sound(la_4_s, n4 * 2)
    await runloop.sleep_ms(n8)

    await play_sound(re_5, n4)
    await play_sound(re_5, n4)
    await play_sound(re_5_s, n8)
    await play_sound(re_5_s, n8)
    await play_sound(re_5, n8)
    await play_sound(do_5, n4)
    await play_sound(re_5_s, n4)
    await play_sound(re_5, n4 * 4)
    await runloop.sleep_ms(n8)

    await play_sound(do_5, n4 * 2)
    await play_sound(fa_5, n4 * 2)
    await play_sound(re_5, n4 * 4)


async def never_gonna_give_you_up():
    """ Never Gonna Give You Up (Rick Astley) を演奏する """
    n4, n8, n16 = bpm_to_note_durations_ms(bpm=114)

    # Never Gonna
    await play_sound(so_4_s, n16)
    await play_sound(la_4_s, n16)
    await play_sound(do_5_s, n16)
    await play_sound(la_4_s, n16)

    # Give You Up
    await play_sound(fa_5, n16)
    await runloop.sleep_ms(n8)
    await play_sound(fa_5, n16)
    await runloop.sleep_ms(n8)
    await play_sound(re_5_s, n4 + n8)
    # Never Gonna
    await play_sound(so_4_s, n16)
    await play_sound(la_4_s, n16)
    await play_sound(do_5_s, n16)
    await play_sound(la_4_s, n16)

    # Let you down
    await play_sound(re_5_s, n16)
    await runloop.sleep_ms(n8)
    await play_sound(re_5_s, n16)
    await runloop.sleep_ms(n8)
    await play_sound(do_5_s, n8 + n16)
    await play_sound(do_5, n16)
    await play_sound(la_4_s, n8)
    # Never Gonna
    await play_sound(so_4_s, n16)
    await play_sound(la_4_s, n16)
    await play_sound(do_5_s, n16)
    await play_sound(la_4_s, n16)

    # Run around and desert you
    await play_sound(do_5_s, n4)
    await play_sound(re_5_s, n8)
    await play_sound(do_5, n8 + n16)
    await play_sound(la_4_s, n16)
    await play_sound(so_4_s, n4)
    await play_sound(so_4_s, n8)
    await play_sound(re_5_s, n4)
    await play_sound(do_5_s, n4 * 2)
    # Never Gonna
    await play_sound(so_4_s, n16)
    await play_sound(la_4_s, n16)
    await play_sound(do_5_s, n16)
    await play_sound(la_4_s, n16)

    # Make you cry
    await play_sound(fa_5, n16)
    await runloop.sleep_ms(n8)
    await play_sound(fa_5, n16)
    await runloop.sleep_ms(n8)
    await play_sound(re_5_s, n4 + n8)
    # Never Gonna
    await play_sound(so_4_s, n16)
    await play_sound(la_4_s, n16)
    await play_sound(do_5_s, n16)
    await play_sound(la_4_s, n16)

    # Say goodbye
    await play_sound(so_5_s, n4)
    await play_sound(do_5, n8)
    await play_sound(do_5_s, n8 + n16)
    await play_sound(do_5, n16)
    await play_sound(la_4_s, n8)
    # Never Gonna
    await play_sound(so_4_s, n16)
    await play_sound(la_4_s, n16)
    await play_sound(do_5_s, n16)
    await play_sound(la_4_s, n16)

    # Tell lie and hurt you
    await play_sound(do_5_s, n4)
    await play_sound(re_5_s, n8)
    await play_sound(do_5, n8 + n16)
    await play_sound(la_4_s, n16)
    await play_sound(so_4_s, n4)
    await play_sound(so_4_s, n8)
    await play_sound(re_5_s, n4)
    await play_sound(do_5_s, n4 * 3)


async def sandstorm():
    """ Sandstorm (Darude) を演奏する """
    n4, n8, n16 = bpm_to_note_durations_ms(bpm=136)

    # TODO
    await play_sound(so_4_s, n16)


async def etenraku():
    """ 越天楽 を演奏する """
    n4, n8, n16 = bpm_to_note_durations_ms(bpm=136)

    # TODO
    await play_sound(so_4_s, n16)


async def play_random_song():
    random_value = random.randint(1, 5)

    await runloop.sleep_ms(500)

    if random_value == 1:
        await yajuu()
    elif random_value == 2:
        await tidus()
    elif random_value == 3:
        await never_gonna_give_you_up()
    elif random_value == 4:
        await sandstorm()
    elif random_value == 5:
        await etenraku()

    await play_random_song()


# ────────────────────────────────────────────────────────
# controllers\drive_controller.py
# ────────────────────────────────────────────────────────
async def rotation(degrees: int, power: int = 100):
    """ 回転操作を行う """
    await motor_pair.move_for_degrees(M_PAIR, degrees * 2, 100, velocity=power_percentage_to_velocity(power))


async def precise_rotation(degrees: int):
    """ 正確な回転操作を行う """

    reset_yaw_value()
    await runloop.sleep_ms(WHILE_INTERVAL)  # reset_yaw_valueが実際には非同期更新のため、少し待つ

    while abs(get_yaw()) > 5:
        await runloop.sleep_ms(WHILE_INTERVAL)

    retry_count = 0

    while True:
        power, finished = get_data_for_precise_rotation(degrees)

        if finished or retry_count > 100:  # 約1秒が経過した時点でタイムアウト
            motor_pair.stop(M_PAIR)
            break

        velocity = power_percentage_to_velocity(power)
        motor_pair.move_tank(M_PAIR, velocity, -velocity)

        await runloop.sleep_ms(WHILE_INTERVAL)
        retry_count += 1

    reset_yaw_value()


async def going_straight(distance: int, power: int = 100):
    """ distanceにはcmの距離を記載する """
    await motor_pair.move_for_degrees(M_PAIR, cm_to_degrees(distance), 0, velocity=power_percentage_to_velocity(power))


def move_infinite(power: int = 100):
    """ stop_motorが実行されるまで無限に進む """
    motor_pair.move(M_PAIR, 0, velocity=power_percentage_to_velocity(power))


def tank_move_infinite(left: int, right: int):
    """ left, rightには左右モーターのパワー（%）を指定する """
    motor_pair.move_tank(M_PAIR, power_percentage_to_velocity(left), power_percentage_to_velocity(right))


async def follow_black_line_until(predicate = lambda: False, power: int = 100):
    """ ある条件が満たされるまで黒色の線を追尾する（predicateに永遠にFalseを返す関数を指定すると無限に走行） """

    velocity = power_percentage_to_velocity(power)

    while not predicate():
        diff = get_reflection_difference(port.A, port.B)
        steering = clamp(diff * LINE_TRACE_ROTATION_KP, minimum=-LINE_TRACE_MAX_STEERING, maximum=LINE_TRACE_MAX_STEERING)

        motor_pair.move(M_PAIR, steering, velocity=velocity)

        await runloop.sleep_ms(WHILE_INTERVAL)

    motor_pair.stop(M_PAIR)


def stop_motor():
    """ モーターの動作を停止する """
    motor_pair.stop(M_PAIR)


# ────────────────────────────────────────────────────────
# main.py
# ────────────────────────────────────────────────────────
async def game1():
    await follow_black_line_until(predicate=lambda: False, power=100)


async def game2():
    await follow_black_line_until(predicate=lambda: is_distance_less_than_or_equal(port.F, 25, DistanceUnit.CM), power=100)
    await rotation(degrees=180)
    await follow_black_line_until(predicate=lambda: False, power=100)


runloop.run(play_random_song(), game1())
